#include "ui_effect.h"

const char UI_EFFECT_HTML[] =
    "        <div class=\"card\">\n"
    "          <h1>Effect</h1>\n"
    "          <p>WLED-style ESP-IDF control surface with built-in and custom palettes for a 27-pixel ring on GPIO16.</p>\n"
    "          <div class=\"row\">\n"
    "            <button id=\"toggleBtn\">Toggle Power</button>\n"
    "            <button id=\"suspendBtn\" class=\"secondary\">Suspend</button>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <div><label for=\"color\">Primary Color</label><input id=\"color\" type=\"color\" value=\"#ff7810\"></div>\n"
    "            <div><label for=\"brightness\">Brightness</label><input id=\"brightness\" type=\"range\" min=\"0\" max=\"255\" value=\"160\"></div>\n"
    "            <div><label for=\"effect\">Effect</label><select id=\"effect\"><option value=\"0\">Solid</option><option value=\"1\">Breathe</option><option value=\"2\">Rainbow</option><option value=\"3\">Chase</option><option value=\"4\">Color Wipe</option><option value=\"5\">Twinkle</option><option value=\"6\">Scanner</option><option value=\"7\">Sparkle</option><option value=\"8\">Swoosh</option><option value=\"9\">Swoosh (Reverse)</option><option value=\"10\">Shrink</option><option value=\"11\">Rotation</option><option value=\"12\">Point</option><option value=\"13\">Breathe Edge</option></select></div>\n"
    "            <div id=\"paletteRow\"><label for=\"palette\">Palette</label><select id=\"palette\"></select></div>\n"
    "            <div><label for=\"speed\">Speed</label><input id=\"speed\" type=\"range\" min=\"1\" max=\"255\" value=\"128\"></div>\n"
    "            <div id=\"swooshBgRow\" style=\"display:none\"><label for=\"swooshBgPalette\">Background Palette</label><select id=\"swooshBgPalette\"></select></div>\n"
    "            <div id=\"swooshLeftRow\" style=\"display:none\"><label for=\"swooshLeftPalette\">Left Palette</label><select id=\"swooshLeftPalette\"></select></div>\n"
    "            <div id=\"swooshRightRow\" style=\"display:none\"><label for=\"swooshRightPalette\">Right Palette</label><select id=\"swooshRightPalette\"></select></div>\n"
    "            <div id=\"sideLengthRow\" style=\"display:none\"><label for=\"sidePaletteLength\">Side Palette Length</label><input id=\"sidePaletteLength\" type=\"number\" min=\"1\" max=\"14\" value=\"5\"></div>\n"
    "            <div id=\"shrinkBgRow\" style=\"display:none\"><label for=\"shrinkBgPalette\">Background Palette</label><select id=\"shrinkBgPalette\"></select></div>\n"
    "            <div id=\"shrinkBarRow\" style=\"display:none\"><label for=\"shrinkBarPalette\">Bar Palette</label><select id=\"shrinkBarPalette\"></select></div>\n"
    "            <div id=\"shrinkLenRow\" style=\"display:none\"><label for=\"shrinkLength\">Shrink Length</label><input id=\"shrinkLength\" type=\"number\" min=\"1\" max=\"9\" value=\"4\"></div>\n"
    "            <div id=\"shrinkGapRow\" style=\"display:none\"><label for=\"shrinkGap\">Shrink Gap</label><input id=\"shrinkGap\" type=\"range\" min=\"0\" max=\"60\" value=\"6\"></div>\n"
    "            <div id=\"rotationBgRow\" style=\"display:none\"><label for=\"rotationBgPalette\">Background Palette</label><select id=\"rotationBgPalette\"></select></div>\n"
    "            <div id=\"rotationPaletteRow\" style=\"display:none\"><label for=\"rotationPalette\">Rotation Palette</label><select id=\"rotationPalette\"></select></div>\n"
    "            <div id=\"rotationLenRow\" style=\"display:none\"><label for=\"rotationLength\">Rotation Length</label><input id=\"rotationLength\" type=\"number\" min=\"2\" max=\"9\" value=\"2\"></div>\n"
    "            <div id=\"rotationGapRow\" style=\"display:none\"><label for=\"rotationGap\">Rotation Gap</label><input id=\"rotationGap\" type=\"range\" min=\"0\" max=\"60\" value=\"6\"></div>\n"
    "            <div id=\"rotationCcwRow\" style=\"display:none\"><label for=\"rotationCcw\">Counterclockwise</label><input id=\"rotationCcw\" type=\"checkbox\"></div>\n"
    "            <div id=\"chaseBgRow\" style=\"display:none\"><label for=\"chaseBgPalette\">Background Palette</label><select id=\"chaseBgPalette\"></select></div>\n"
    "            <div id=\"chasePaletteRow\" style=\"display:none\"><label for=\"chasePalette\">Chase Palette</label><select id=\"chasePalette\"></select></div>\n"
    "            <div id=\"chaseLenRow\" style=\"display:none\"><label for=\"chaseLength\">Chase Length</label><input id=\"chaseLength\" type=\"number\" min=\"1\" max=\"27\" value=\"5\"></div>\n"
    "            <div id=\"pointPaletteRow\" style=\"display:none\"><label for=\"pointPalette\">Point Palette</label><select id=\"pointPalette\"></select></div>\n"
    "            <div id=\"pointBgRow\" style=\"display:none\"><label for=\"pointBgPalette\">Background Palette</label><select id=\"pointBgPalette\"></select></div>\n"
    "            <div id=\"pointLenRow\" style=\"display:none\"><label for=\"pointLength\">Point Length</label><input id=\"pointLength\" type=\"number\" min=\"1\" max=\"14\" value=\"3\"></div>\n"
    "            <div id=\"pointTotalRow\" style=\"display:none\"><label for=\"pointTotal\">Total Length</label><input id=\"pointTotal\" type=\"number\" min=\"1\" max=\"14\" value=\"14\"></div>\n"
    "            <div id=\"pointModeRow\" style=\"display:none\"><label for=\"pointMode\">Repeat</label><select id=\"pointMode\"><option value=\"1\">Single</option><option value=\"2\">Double</option><option value=\"3\">Triple</option></select></div>\n"
    "            <div id=\"pointGapRow\" style=\"display:none\"><label for=\"pointGap\">Gap</label><input id=\"pointGap\" type=\"range\" min=\"0\" max=\"60\" value=\"8\"></div>\n"
    "            <div id=\"edgePaletteRow\" style=\"display:none\"><label for=\"edgePalette\">Edge Palette</label><select id=\"edgePalette\"></select></div>\n"
    "            <div id=\"edgeLenRow\" style=\"display:none\"><label for=\"edgeLength\">Edge Length</label><input id=\"edgeLength\" type=\"number\" min=\"1\" max=\"27\" value=\"2\"></div>\n"
    "            <div id=\"edgeModeRow\" style=\"display:none\"><label for=\"edgeMode\">Repeat</label><select id=\"edgeMode\"><option value=\"1\">Single</option><option value=\"2\">Double</option><option value=\"3\">Triple</option></select></div>\n"
    "            <div id=\"edgeGapRow\" style=\"display:none\"><label for=\"edgeGap\">Gap</label><input id=\"edgeGap\" type=\"range\" min=\"0\" max=\"60\" value=\"8\"></div>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <button id=\"applyBtn\">Apply State</button>\n"
    "            <button id=\"saveScenarioBtn\" class=\"secondary\">Save Scenario</button>\n"
    "          </div>\n"
    "          <p id=\"deviceInfo\" class=\"pill\">Loading device info...</p>\n"
    "          <p>API: <code>/json/state</code>, <code>/json/info</code>, <code>/json/palettes</code>, <code>/win</code></p>\n"
    "        </div>\n";
