#include "esp_err.h"
#include "esp_http_server.h"

#include "app_config.h"
#include "http_server.h"
#include "ui_effect.h"
#include "ui_page.h"
#include "ui_palette.h"
#include "ui_scenario.h"

static const char UI_PAGE_HEAD[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "  <title>Light Ring Control</title>\n"
    "  <style>\n"
    "    :root { color-scheme: light; --bg:#f6efe3; --card:rgba(255,250,243,0.88); --ink:#1f1b16; --accent:#d95f39; --accent-2:#0d7b77; --line:#dcc8b0; --muted:#6f6355; }\n"
    "    * { box-sizing:border-box; }\n"
    "    body { margin:0; font-family:'Segoe UI',sans-serif; background:radial-gradient(circle at top,#fffaf4, #f2e4d1 52%, #dfc9aa); color:var(--ink); }\n"
    "    main { max-width:1120px; margin:0 auto; padding:28px 18px 44px; }\n"
    "    .page { display:grid; gap:20px; grid-template-columns:minmax(0, 1.2fr) minmax(320px, 0.8fr); align-items:start; }\n"
    "    .stack { display:grid; gap:16px; }\n"
    "    .card { background:var(--card); backdrop-filter:blur(14px); border:1px solid var(--line); border-radius:24px; padding:24px; box-shadow:0 18px 50px rgba(70,40,20,0.12); }\n"
    "    h1 { margin:0 0 10px; font-size:clamp(28px,5vw,44px); }\n"
    "    h2 { margin:0 0 10px; font-size:20px; }\n"
    "    p { line-height:1.5; }\n"
    "    label { display:block; font-size:14px; margin-bottom:8px; text-transform:uppercase; letter-spacing:0.08em; }\n"
    "    input, select, button { width:100%; border-radius:14px; border:1px solid var(--line); padding:12px 14px; font-size:16px; }\n"
    "    input[type=range] { padding:0; }\n"
    "    input[type=color] { min-height:52px; padding:6px; }\n"
    "    input[type=checkbox] { width:20px; height:20px; min-height:20px; padding:0; accent-color:var(--accent); }\n"
    "    button { background:linear-gradient(135deg,var(--accent),#f08b54); color:white; border:none; font-weight:600; cursor:pointer; }\n"
    "    button.secondary { background:linear-gradient(135deg,var(--accent-2),#35a6a2); }\n"
    "    button.ghost { background:white; color:var(--ink); border:1px solid var(--line); }\n"
    "    button.danger { color:#b23b1e; border-color:#e7b6a6; }\n"
    "    button.danger:hover { background:#fbeae3; }\n"
    "    button:disabled { opacity:0.55; cursor:not-allowed; }\n"
    "    .row { display:flex; gap:12px; align-items:center; }\n"
    "    .row > * { flex:1; }\n"
    "    .grid { display:grid; gap:16px; grid-template-columns:repeat(auto-fit,minmax(220px,1fr)); margin-top:20px; }\n"
    "    .pill { display:inline-flex; align-items:center; gap:8px; margin-top:12px; padding:8px 12px; border-radius:999px; background:#fff; border:1px solid var(--line); font-size:14px; }\n"
    "    code { background:#fff; padding:2px 6px; border-radius:8px; }\n"
    "    .note { margin:0; color:var(--muted); font-size:14px; }\n"
    "    .palette-grid { display:grid; gap:12px; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); }\n"
    "    .palette-card { position:relative; width:100%; padding:0; overflow:hidden; text-align:left; background:#fff; color:var(--ink); border:1px solid var(--line); border-radius:18px; transition:transform .18s ease, box-shadow .18s ease, border-color .18s ease; }\n"
    "    .palette-card:hover { transform:translateY(-2px); box-shadow:0 10px 24px rgba(40,24,12,0.12); }\n"
    "    .palette-card.active { border-color:var(--accent); box-shadow:0 0 0 2px rgba(217,95,57,0.18); }\n"
    "    .palette-card.editable::after { content:'Custom'; position:absolute; top:10px; right:10px; padding:4px 8px; border-radius:999px; background:rgba(255,255,255,0.92); color:var(--ink); font-size:11px; }\n"
    "    .palette-preview { min-height:68px; display:grid; grid-template-columns:repeat(16,1fr); overflow:hidden; border-radius:16px; }\n"
    "    .palette-preview > div { min-height:68px; }\n"
    "    .palette-meta { padding:12px 14px 14px; }\n"
    "    .palette-meta strong { display:block; font-size:15px; }\n"
    "    .palette-meta span { color:var(--muted); font-size:13px; }\n"
    "    .editor-shell { display:grid; gap:16px; }\n"
    "    .editor-options { align-items:stretch; }\n"
    "    .editor-options > .toggle-row { flex:0 0 220px; }\n"
    "    .editor-header { display:flex; gap:12px; align-items:center; justify-content:space-between; }\n"
    "    .editor-header > * { flex:1; }\n"
    "    .actions { display:flex; gap:10px; justify-content:flex-end; }\n"
    "    .actions button, .toolbar button { width:auto; }\n"
    "    .toolbar { display:flex; gap:10px; flex-wrap:wrap; }\n"
    "    .stop-list { display:grid; gap:10px; }\n"
    "    .stop-row { display:grid; gap:10px; grid-template-columns:88px minmax(0,1fr) auto; align-items:end; padding:12px; border:1px solid var(--line); border-radius:16px; background:rgba(255,255,255,0.76); }\n"
    "    .mini-label { font-size:12px; color:var(--muted); margin-bottom:6px; text-transform:uppercase; letter-spacing:0.08em; }\n"
    "    .color-chip { min-height:52px; border-radius:14px; border:1px solid var(--line); background:#fff; cursor:pointer; box-shadow:inset 0 0 0 1px rgba(255,255,255,0.45); }\n"
    "    dialog.color-dialog { border:none; border-radius:22px; padding:0; max-width:420px; width:min(92vw, 420px); box-shadow:0 24px 60px rgba(20,10,4,0.22); }\n"
    "    dialog.color-dialog::backdrop { background:rgba(20,10,4,0.32); backdrop-filter:blur(2px); }\n"
    "    .dialog-body { padding:22px; display:grid; gap:14px; background:#fffaf4; }\n"
    "    .dialog-grid { display:grid; gap:12px; grid-template-columns:repeat(3, minmax(0,1fr)); }\n"
    "    .dialog-grid .wide { grid-column:1 / -1; }\n"
    "    .dialog-actions { display:flex; gap:10px; justify-content:flex-end; }\n"
    "    .dialog-actions button { width:auto; }\n"
    "    .dialog-body input[type=number], .dialog-body input[type=text], .dialog-body input[type=color] { width:100%; }\n"
    "    .dialog-body input[type=text] { text-transform:uppercase; }\n"
    "    label.toggle-row { display:flex; align-items:center; gap:10px; margin:0; padding:14px 16px; border:1px solid var(--line); border-radius:16px; background:rgba(255,255,255,0.76); }\n"
    "    label.toggle-row span { font-size:14px; text-transform:uppercase; letter-spacing:0.08em; }\n"
    "    .stop-row button { width:auto; }\n"
    "    .scenario-list { display:grid; gap:10px; }\n"
    "    .scenario-row { display:flex; align-items:center; justify-content:space-between; gap:12px; padding:12px 14px; border:1px solid var(--line); border-radius:14px; background:rgba(255,255,255,0.78); cursor:pointer; user-select:none; transition:border-color 0.15s ease; }\n"
    "    .scenario-row:hover { border-color:#ff7810; }\n"
    "    .scenario-name { display:flex; flex-direction:column; gap:3px; min-width:0; }\n"
    "    .scenario-name strong { font-size:15px; word-break:break-word; }\n"
    "    .scenario-name span { font-size:12px; color:var(--muted); text-transform:uppercase; letter-spacing:0.06em; }\n"
    "    .scenario-row button.scenario-info { width:auto; padding:8px 14px; flex:0 0 auto; }\n"
    "    .scenario-row button.scenario-delete { width:auto; padding:8px 14px; flex:0 0 auto; }\n"
    "    .scenario-detail-list { display:grid; gap:10px; }\n"
    "    .detail-row { display:flex; align-items:center; justify-content:space-between; gap:16px; padding:10px 12px; border:1px solid var(--line); border-radius:12px; background:#fffaf4; }\n"
    "    .detail-row span { color:var(--muted); font-size:13px; }\n"
    "    #scenarioNameInput { text-transform:none; }\n"
    "    @media (max-width: 880px) { .page { grid-template-columns:1fr; } .actions { justify-content:flex-start; } }\n"
    "    @media (max-width: 640px) { .row.editor-options { flex-direction:column; } .editor-options > .toggle-row { flex:1 1 auto; } .stop-row { grid-template-columns:1fr; } .dialog-grid { grid-template-columns:1fr; } }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <main>\n"
    "    <div class=\"page\">\n"
    "      <div class=\"stack\">\n";

static const char UI_PAGE_COLUMN_BREAK[] =
    "      </div>\n"
    "      <div class=\"stack\">\n";

static const char UI_PAGE_STRUCT_CLOSE[] =
    "      </div>\n"
    "    </div>\n";

static const char UI_PAGE_TAIL[] =
    "  </main>\n"
    "  <script>\n"
    "    const colorInput = document.getElementById('color');\n"
    "    const brightnessInput = document.getElementById('brightness');\n"
    "    const speedInput = document.getElementById('speed');\n"
    "    const effectInput = document.getElementById('effect');\n"
    "    const paletteInput = document.getElementById('palette');\n"
    "    const swooshBgPaletteInput = document.getElementById('swooshBgPalette');\n"
    "    const swooshLeftPaletteInput = document.getElementById('swooshLeftPalette');\n"
    "    const swooshRightPaletteInput = document.getElementById('swooshRightPalette');\n"
    "    const sideLengthInput = document.getElementById('sidePaletteLength');\n"
    "    const shrinkBgPaletteInput = document.getElementById('shrinkBgPalette');\n"
    "    const shrinkBarPaletteInput = document.getElementById('shrinkBarPalette');\n"
    "    const shrinkLenInput = document.getElementById('shrinkLength');\n"
    "    const shrinkGapInput = document.getElementById('shrinkGap');\n"
    "    const rotationBgPaletteInput = document.getElementById('rotationBgPalette');\n"
    "    const rotationPaletteInput = document.getElementById('rotationPalette');\n"
    "    const rotationLenInput = document.getElementById('rotationLength');\n"
    "    const rotationGapInput = document.getElementById('rotationGap');\n"
    "    const rotationCcwInput = document.getElementById('rotationCcw');\n"
    "    const chaseBgPaletteInput = document.getElementById('chaseBgPalette');\n"
    "    const chasePaletteInput = document.getElementById('chasePalette');\n"
    "    const chaseLenInput = document.getElementById('chaseLength');\n"
    "    const pointPaletteInput = document.getElementById('pointPalette');\n"
    "    const pointBgPaletteInput = document.getElementById('pointBgPalette');\n"
    "    const pointLenInput = document.getElementById('pointLength');\n"
    "    const pointTotalInput = document.getElementById('pointTotal');\n"
    "    const pointModeInput = document.getElementById('pointMode');\n"
    "    const pointGapInput = document.getElementById('pointGap');\n"
    "    const edgePaletteInput = document.getElementById('edgePalette');\n"
    "    const edgeLenInput = document.getElementById('edgeLength');\n"
    "    const edgeModeInput = document.getElementById('edgeMode');\n"
    "    const edgeGapInput = document.getElementById('edgeGap');\n"
    "    const paletteRow = document.getElementById('paletteRow');\n"
    "    const swooshBgRow = document.getElementById('swooshBgRow');\n"
    "    const swooshLeftRow = document.getElementById('swooshLeftRow');\n"
    "    const swooshRightRow = document.getElementById('swooshRightRow');\n"
    "    const sideLengthRow = document.getElementById('sideLengthRow');\n"
    "    const shrinkBgRow = document.getElementById('shrinkBgRow');\n"
    "    const shrinkBarRow = document.getElementById('shrinkBarRow');\n"
    "    const shrinkLenRow = document.getElementById('shrinkLenRow');\n"
    "    const shrinkGapRow = document.getElementById('shrinkGapRow');\n"
    "    const rotationBgRow = document.getElementById('rotationBgRow');\n"
    "    const rotationPaletteRow = document.getElementById('rotationPaletteRow');\n"
    "    const rotationLenRow = document.getElementById('rotationLenRow');\n"
    "    const rotationGapRow = document.getElementById('rotationGapRow');\n"
    "    const rotationCcwRow = document.getElementById('rotationCcwRow');\n"
    "    const chaseBgRow = document.getElementById('chaseBgRow');\n"
    "    const chasePaletteRow = document.getElementById('chasePaletteRow');\n"
    "    const chaseLenRow = document.getElementById('chaseLenRow');\n"
    "    const pointPaletteRow = document.getElementById('pointPaletteRow');\n"
    "    const pointBgRow = document.getElementById('pointBgRow');\n"
    "    const pointLenRow = document.getElementById('pointLenRow');\n"
    "    const pointTotalRow = document.getElementById('pointTotalRow');\n"
    "    const pointModeRow = document.getElementById('pointModeRow');\n"
    "    const pointGapRow = document.getElementById('pointGapRow');\n"
    "    const edgePaletteRow = document.getElementById('edgePaletteRow');\n"
    "    const edgeLenRow = document.getElementById('edgeLenRow');\n"
    "    const edgeModeRow = document.getElementById('edgeModeRow');\n"
    "    const edgeGapRow = document.getElementById('edgeGapRow');\n"
    "    const suspendBtn = document.getElementById('suspendBtn');\n"
    "    const deviceInfo = document.getElementById('deviceInfo');\n"
    "    const paletteGallery = document.getElementById('paletteGallery');\n"
    "    const editorHint = document.getElementById('editorHint');\n"
    "    const customPaletteName = document.getElementById('customPaletteName');\n"
    "    const circlePaletteInput = document.getElementById('circlePaletteInput');\n"
    "    const stopList = document.getElementById('stopList');\n"
    "    const editorPreview = document.getElementById('editorPreview');\n"
    "    const addStopBtn = document.getElementById('addStopBtn');\n"
    "    const savePaletteBtn = document.getElementById('savePaletteBtn');\n"
    "    const deletePaletteBtn = document.getElementById('deletePaletteBtn');\n"
    "    const newPaletteBtn = document.getElementById('newPaletteBtn');\n"
    "    const reloadPalettesBtn = document.getElementById('reloadPalettesBtn');\n"
    "    const colorDialog = document.getElementById('colorDialog');\n"
    "    const colorDialogHint = document.getElementById('colorDialogHint');\n"
    "    const dialogColorPicker = document.getElementById('dialogColorPicker');\n"
    "    const dialogHexInput = document.getElementById('dialogHexInput');\n"
    "    const dialogRedInput = document.getElementById('dialogRedInput');\n"
    "    const dialogGreenInput = document.getElementById('dialogGreenInput');\n"
    "    const dialogBlueInput = document.getElementById('dialogBlueInput');\n"
    "    const dialogCancelBtn = document.getElementById('dialogCancelBtn');\n"
    "    const dialogApplyBtn = document.getElementById('dialogApplyBtn');\n"
    "    const saveScenarioBtn = document.getElementById('saveScenarioBtn');\n"
    "    const reloadScenariosBtn = document.getElementById('reloadScenariosBtn');\n"
    "    const scenarioList = document.getElementById('scenarioList');\n"
    "    const scenarioHint = document.getElementById('scenarioHint');\n"
    "    const scenarioSaveDialog = document.getElementById('scenarioSaveDialog');\n"
    "    const scenarioNameInput = document.getElementById('scenarioNameInput');\n"
    "    const scenarioSaveCancelBtn = document.getElementById('scenarioSaveCancelBtn');\n"
    "    const scenarioSaveConfirmBtn = document.getElementById('scenarioSaveConfirmBtn');\n"
    "    const scenarioDetailDialog = document.getElementById('scenarioDetailDialog');\n"
    "    const scenarioDetailTitle = document.getElementById('scenarioDetailTitle');\n"
    "    const scenarioDetailBody = document.getElementById('scenarioDetailBody');\n"
    "    const scenarioDetailCloseBtn = document.getElementById('scenarioDetailCloseBtn');\n"
    "    const exportBackupBtn = document.getElementById('exportBackupBtn');\n"
    "    const importBackupBtn = document.getElementById('importBackupBtn');\n"
    "    const importBackupInput = document.getElementById('importBackupInput');\n"
    "    const backupHint = document.getElementById('backupHint');\n"
    "    let lastOn = true;\n"
    "    let lastPaused = false;\n"
    "    let paletteCatalog = [];\n"
    "    let scenarios = [];\n"
    "    let selectedPaletteId = 0;\n"
    "    let editingPaletteId = null;\n"
    "    let editingStops = [];\n"
    "    let editingPaletteCircle = false;\n"
    "    let editingColorIndex = null;\n"
    "    let detailScenarioId = null;\n"
    "    const ledCount = " STRINGIFY(CONFIG_LIGHT_RING_LED_COUNT) ";\n"
    "    function rgbToHex(rgb) { return '#' + rgb.map(v => Number(v).toString(16).padStart(2, '0')).join(''); }\n"
    "    function hexToRgb(hex) { const value = hex.replace('#', ''); return [parseInt(value.slice(0,2),16), parseInt(value.slice(2,4),16), parseInt(value.slice(4,6),16)]; }\n"
    "    function normalizeHexInput(value) { const raw = String(value || '').trim().replace(/^#/, '').toUpperCase(); if (!/^[0-9A-F]{0,6}$/.test(raw)) return null; return '#' + raw; }\n"
    "    function isCompleteHex(value) { return /^#[0-9A-F]{6}$/.test(String(value || '').toUpperCase()); }\n"
    "    function clampLedIndex(value) { return Math.max(1, Math.min(ledCount, Number(value) || 1)); }\n"
    "    function paletteIndexToLedIndex(value, circular = editingPaletteCircle) { const clamped = Math.max(0, Math.min(255, Number(value) || 0)); if (ledCount <= 1) return 1; if (circular) return 1 + Math.floor((clamped * ledCount) / 256); return 1 + Math.round((clamped * (ledCount - 1)) / 255); }\n"
    "    function ledIndexToPaletteIndex(value, circular = editingPaletteCircle) { const clamped = clampLedIndex(value); if (ledCount <= 1) return 0; if (circular) return Math.floor(((clamped - 1) * 256) / ledCount); return Math.round(((clamped - 1) * 255) / (ledCount - 1)); }\n"
    "    function normalizeStops(stops) { return (Array.isArray(stops) ? stops : []).map(stop => ({ index: Number(stop[0] ?? stop.index ?? 0), rgb: Array.isArray(stop) ? [Number(stop[1] ?? 0), Number(stop[2] ?? 0), Number(stop[3] ?? 0)] : [Number(stop.red ?? 0), Number(stop.green ?? 0), Number(stop.blue ?? 0)] })).sort((a, b) => a.index - b.index); }\n"
    "    function seedPaletteStops() { return [{ index: 0, rgb: hexToRgb(colorInput ? colorInput.value : '#ff7810') }, { index: 255, rgb: [255, 255, 255] }]; }\n"
    "    function nextEmptyCustomPalette() { return paletteCatalog.find(item => item.editable && item.empty); }\n"
    "    function clampChannel(value) { return Math.max(0, Math.min(255, Number(value) || 0)); }\n"
    "    function sampleStopGradient(left, right, span, distance) { if (span <= 0) return [...right.rgb]; const progress = Math.max(0, Math.min(255, Math.round((distance * 255) / span))); const remain = 255 - progress; return [0, 1, 2].map(channel => Math.round(((left.rgb[channel] * remain) + (right.rgb[channel] * progress)) / 255)); }\n"
    "    function sampleStops(stops, circular, target) { if (!stops.length) return [0, 0, 0]; if (stops.length === 1) return [...stops[0].rgb]; if (!circular) { const first = stops[0]; const last = stops[stops.length - 1]; if (target <= first.index) return [...first.rgb]; if (target >= last.index) return [...last.rgb]; for (let index = 1; index < stops.length; index += 1) { const right = stops[index]; const left = stops[index - 1]; if (target > right.index) continue; return sampleStopGradient(left, right, right.index - left.index, target - left.index); } return [...last.rgb]; } for (let index = 0; index < stops.length; index += 1) { const left = stops[index]; const right = stops[(index + 1) % stops.length]; const span = right.index >= left.index ? (right.index - left.index) : (256 + right.index - left.index); const distance = target >= left.index ? (target - left.index) : (256 + target - left.index); if (distance <= span) return sampleStopGradient(left, right, span, distance); } return [...stops[stops.length - 1].rgb]; }\n"
    "    function previewColorsFromStops(stops, circular) { return Array.from({ length: 16 }, (_, entry) => { const target = entry === 15 ? 255 : (entry << 4); return [target, ...sampleStops(stops, circular, target)]; }); }\n"
    "    function syncDialogFromRgb(rgb) { const safe = [clampChannel(rgb[0]), clampChannel(rgb[1]), clampChannel(rgb[2])]; dialogColorPicker.value = rgbToHex(safe); dialogHexInput.value = rgbToHex(safe).toUpperCase(); dialogRedInput.value = String(safe[0]); dialogGreenInput.value = String(safe[1]); dialogBlueInput.value = String(safe[2]); }\n"
    "    function dialogRgb() { return [clampChannel(dialogRedInput.value), clampChannel(dialogGreenInput.value), clampChannel(dialogBlueInput.value)]; }\n"
    "    function openColorDialog(index) { if (Number.isNaN(index) || !editingStops[index] || !colorDialog) return; editingColorIndex = index; colorDialogHint.textContent = `Editing stop ${index + 1}. Use color, HEX, or RGB.`; syncDialogFromRgb(editingStops[index].rgb); if (typeof colorDialog.showModal === 'function') { colorDialog.showModal(); } }\n"
    "    function closeColorDialog() { if (colorDialog && colorDialog.open) colorDialog.close(); editingColorIndex = null; }\n"
    "    function applyDialogColor() { if (editingColorIndex === null || !editingStops[editingColorIndex]) { closeColorDialog(); return; } editingStops[editingColorIndex].rgb = dialogRgb(); renderPreview(editorPreview, editingStops.map(stop => [stop.index, ...stop.rgb])); renderStopEditor(); closeColorDialog(); }\n"
    "    function renderPreview(target, colors) { if (!target) return; target.innerHTML = ''; (colors || []).forEach(entry => { const swatch = document.createElement('div'); const rgb = Array.isArray(entry) ? entry.slice(1,4) : entry.rgb; swatch.style.background = `rgb(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`; target.appendChild(swatch); }); }\n"
    "    function renderPaletteSelect() { if (!paletteInput || !swooshBgPaletteInput || !swooshLeftPaletteInput || !swooshRightPaletteInput) return; const current = String(selectedPaletteId); const options = paletteCatalog.filter(item => !item.empty).map(item => `<option value=\"${item.id}\">${item.name}</option>`).join(''); paletteInput.innerHTML = options; swooshBgPaletteInput.innerHTML = options; swooshLeftPaletteInput.innerHTML = options; swooshRightPaletteInput.innerHTML = options; if (shrinkBgPaletteInput) shrinkBgPaletteInput.innerHTML = options; if (shrinkBarPaletteInput) shrinkBarPaletteInput.innerHTML = options; if (rotationBgPaletteInput) rotationBgPaletteInput.innerHTML = options; if (rotationPaletteInput) rotationPaletteInput.innerHTML = options; if (pointPaletteInput) pointPaletteInput.innerHTML = options; if (pointBgPaletteInput) pointBgPaletteInput.innerHTML = options; if (edgePaletteInput) edgePaletteInput.innerHTML = options; if (chaseBgPaletteInput) chaseBgPaletteInput.innerHTML = options; if (chasePaletteInput) chasePaletteInput.innerHTML = options; if ([...paletteInput.options].some(option => option.value === current)) paletteInput.value = current; }\n"
    "    function activatePaletteCard(id) { if (!paletteGallery) return; [...paletteGallery.children].forEach(card => card.classList.toggle('active', Number(card.dataset.id) === Number(id))); }\n"
    "    function renderStopEditor() { if (!stopList || !editorPreview || !editorHint || !customPaletteName || !circlePaletteInput) return; stopList.innerHTML = ''; const current = paletteCatalog.find(item => Number(item.id) === Number(editingPaletteId)); if (!current) { editorHint.textContent = 'Select a custom palette card or create a new one.'; customPaletteName.value = ''; circlePaletteInput.checked = false; circlePaletteInput.disabled = true; renderPreview(editorPreview, []); return; } circlePaletteInput.disabled = false; circlePaletteInput.checked = editingPaletteCircle; const flowHint = editingPaletteCircle ? 'Circle mode wraps LED 27 back to LED 1.' : 'Linear mode clamps the two ends.'; editorHint.textContent = current.empty ? `Creating ${current.name}. Give it a name and tune its color stops. ${flowHint}` : `Editing custom palette ${current.name}. Stops are saved as WLED-style [index,r,g,b] entries. ${flowHint}`; if (!current.empty && customPaletteName.value === '') customPaletteName.value = current.name; const previewColors = previewColorsFromStops(editingStops, editingPaletteCircle); renderPreview(editorPreview, previewColors.length ? previewColors : (current.colors || [])); editingStops.forEach((stop, index) => { const row = document.createElement('div'); row.className = 'stop-row'; row.innerHTML = `<div><div class=\"mini-label\">Index</div><input type=\"number\" min=\"0\" max=\"255\" value=\"${stop.index}\" data-role=\"index\" data-index=\"${index}\"></div><div><div class=\"mini-label\">Color</div><button type=\"button\" class=\"color-chip\" style=\"background:${rgbToHex(stop.rgb)}\" data-role=\"edit-color\" data-index=\"${index}\" aria-label=\"Edit stop color ${index + 1}\"></button></div><button type=\"button\" class=\"ghost\" data-role=\"remove\" data-index=\"${index}\">Remove</button>`; stopList.appendChild(row); }); }\n"
    "    function renderPaletteGallery() { if (!paletteGallery) return; paletteGallery.innerHTML = ''; paletteCatalog.filter(item => !item.empty).forEach(item => { const card = document.createElement('button'); card.type = 'button'; card.className = `palette-card${item.editable ? ' editable' : ''}${Number(item.id) === Number(selectedPaletteId) ? ' active' : ''}`; card.dataset.id = item.id; const preview = document.createElement('div'); preview.className = 'palette-preview'; (item.colors || []).forEach(entry => { const swatch = document.createElement('div'); const rgb = Array.isArray(entry) ? entry.slice(1,4) : entry.rgb; swatch.style.background = `rgb(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`; preview.appendChild(swatch); }); const meta = document.createElement('div'); meta.className = 'palette-meta'; meta.innerHTML = `<strong>${item.name}</strong><span>${item.editable ? 'Custom editable palette' : 'Built-in palette'}</span>`; card.append(preview, meta); card.addEventListener('click', () => { selectedPaletteId = Number(item.id); if (paletteInput) paletteInput.value = String(selectedPaletteId); activatePaletteCard(selectedPaletteId); if (item.editable) { loadPaletteEditor(item.id); } else { editingPaletteId = null; editingStops = []; renderStopEditor(); } }); paletteGallery.appendChild(card); }); if (newPaletteBtn) { const next = nextEmptyCustomPalette(); newPaletteBtn.disabled = !next; newPaletteBtn.textContent = next ? 'New Custom Palette' : 'Custom Slots Full'; } }\n"
    "    function loadPaletteEditor(id) { const item = paletteCatalog.find(entry => Number(entry.id) === Number(id)); if (!item || !item.editable) return; editingPaletteId = Number(id); customPaletteName.value = item.empty ? '' : item.name; editingPaletteCircle = !!(item.circle ?? item.circular ?? false); editingStops = item.empty ? seedPaletteStops() : normalizeStops(item.stops && item.stops.length ? item.stops : item.colors).slice(0, 27); renderStopEditor(); }\n"
    "    const baseRenderStopEditor = renderStopEditor;\n"
    "    renderStopEditor = function() { baseRenderStopEditor(); stopList.querySelectorAll('[data-role=index]').forEach(input => { input.dataset.role = 'index-led'; input.min = '1'; input.max = String(ledCount); input.step = '1'; input.value = String(clampLedIndex(paletteIndexToLedIndex(input.value, editingPaletteCircle))); const container = input.parentElement; const label = container ? container.querySelector('.mini-label') : null; if (label) label.textContent = 'LED'; }); };\n"
    "    function startNewPalette() { const item = nextEmptyCustomPalette(); if (!item) { editorHint.textContent = 'All custom palette slots are already in use.'; return; } loadPaletteEditor(item.id); }\n"
    "    function updateEffectControls() { const effectId = Number(effectInput.value); const isChase = effectId === 3; const isSwoosh = effectId === 8 || effectId === 9; const isShrink = effectId === 10; const isRotation = effectId === 11; const isPoint = effectId === 12; const isEdge = effectId === 13; paletteRow.style.display = (isChase || isSwoosh || isShrink || isRotation || isPoint || isEdge) ? 'none' : ''; swooshBgRow.style.display = isSwoosh ? '' : 'none'; swooshLeftRow.style.display = isSwoosh ? '' : 'none'; swooshRightRow.style.display = isSwoosh ? '' : 'none'; sideLengthRow.style.display = isSwoosh ? '' : 'none'; shrinkBgRow.style.display = isShrink ? '' : 'none'; shrinkBarRow.style.display = isShrink ? '' : 'none'; shrinkLenRow.style.display = isShrink ? '' : 'none'; shrinkGapRow.style.display = isShrink ? '' : 'none'; if (rotationBgRow) rotationBgRow.style.display = isRotation ? '' : 'none'; if (rotationPaletteRow) rotationPaletteRow.style.display = isRotation ? '' : 'none'; if (rotationLenRow) rotationLenRow.style.display = isRotation ? '' : 'none'; if (rotationGapRow) rotationGapRow.style.display = isRotation ? '' : 'none'; if (rotationCcwRow) rotationCcwRow.style.display = isRotation ? '' : 'none'; if (pointPaletteRow) pointPaletteRow.style.display = isPoint ? '' : 'none'; if (pointBgRow) pointBgRow.style.display = isPoint ? '' : 'none'; if (pointLenRow) pointLenRow.style.display = isPoint ? '' : 'none'; if (pointTotalRow) pointTotalRow.style.display = isPoint ? '' : 'none'; if (pointModeRow) pointModeRow.style.display = isPoint ? '' : 'none'; if (pointGapRow) pointGapRow.style.display = isPoint ? '' : 'none'; if (edgePaletteRow) edgePaletteRow.style.display = isEdge ? '' : 'none'; if (edgeLenRow) edgeLenRow.style.display = isEdge ? '' : 'none'; if (edgeModeRow) edgeModeRow.style.display = isEdge ? '' : 'none'; if (edgeGapRow) edgeGapRow.style.display = isEdge ? '' : 'none'; if (chaseBgRow) chaseBgRow.style.display = isChase ? '' : 'none'; if (chasePaletteRow) chasePaletteRow.style.display = isChase ? '' : 'none'; if (chaseLenRow) chaseLenRow.style.display = isChase ? '' : 'none'; }\n"
    "    async function loadInfo() { const response = await fetch('/json/info'); const info = await response.json(); deviceInfo.textContent = `${info.name} | AP ${info.wifi.ap_ssid} | LEDs ${info.led.count} @ GPIO${info.led.gpio}`; }\n"
    "    async function loadPalettes() { const response = await fetch('/json/palettes'); const json = await response.json(); paletteCatalog = Array.isArray(json.items) ? json.items : []; renderPaletteSelect(); renderPaletteGallery(); if (editingPaletteId !== null) { loadPaletteEditor(editingPaletteId); } else { renderStopEditor(); } }\n"
    "    function updateSuspendButtonLabel() { suspendBtn.textContent = lastPaused ? 'Resume' : 'Suspend'; }\n"
    "    async function loadState() { const response = await fetch('/json/state'); const state = await response.json(); const seg = state.seg && state.seg[0] ? state.seg[0] : {}; const color = seg.col && seg.col[0] ? seg.col[0] : state.color; lastOn = !!state.on; lastPaused = !!state.paused; selectedPaletteId = Number(seg.pal ?? state.pal ?? state.palette ?? 0); updateSuspendButtonLabel(); brightnessInput.value = state.bri ?? 0; speedInput.value = seg.sx ?? state.speed ?? 128; effectInput.value = seg.fx ?? state.fx ?? 0; swooshBgPaletteInput.value = String(seg.bgPal ?? state.bgPal ?? 0); swooshLeftPaletteInput.value = String(seg.leftPal ?? state.leftPal ?? 0); swooshRightPaletteInput.value = String(seg.rightPal ?? state.rightPal ?? 0); sideLengthInput.value = String(seg.leftStops ?? state.leftStops ?? 5); if (shrinkBgPaletteInput) shrinkBgPaletteInput.value = String(seg.shrinkBg ?? state.shrinkBg ?? 0); if (shrinkBarPaletteInput) shrinkBarPaletteInput.value = String(seg.shrinkBar ?? state.shrinkBar ?? 0); if (shrinkLenInput) shrinkLenInput.value = String(seg.shrinkLen ?? state.shrinkLen ?? 4); if (shrinkGapInput) shrinkGapInput.value = String(seg.shrinkGap ?? state.shrinkGap ?? 6); if (rotationBgPaletteInput) rotationBgPaletteInput.value = String(seg.rotBg ?? state.rotBg ?? 0); if (rotationPaletteInput) rotationPaletteInput.value = String(seg.rotPal ?? state.rotPal ?? 0); if (rotationLenInput) rotationLenInput.value = String(seg.rotLen ?? state.rotLen ?? 2); if (rotationGapInput) rotationGapInput.value = String(seg.rotGap ?? state.rotGap ?? 6); if (rotationCcwInput) rotationCcwInput.checked = !!(seg.rotCcw ?? state.rotCcw ?? false); if (pointPaletteInput) pointPaletteInput.value = String(seg.ptPal ?? state.ptPal ?? 0); if (pointBgPaletteInput) pointBgPaletteInput.value = String(seg.ptBg ?? state.ptBg ?? 0); if (pointLenInput) pointLenInput.value = String(seg.ptLen ?? state.ptLen ?? 3); if (pointTotalInput) pointTotalInput.value = String(seg.ptTotal ?? state.ptTotal ?? 14); if (pointModeInput) pointModeInput.value = String(seg.ptMode ?? state.ptMode ?? 1); if (pointGapInput) pointGapInput.value = String(seg.ptGap ?? state.ptGap ?? 8); if (edgePaletteInput) edgePaletteInput.value = String(seg.edgePal ?? state.edgePal ?? 0); if (edgeLenInput) edgeLenInput.value = String(seg.edgeLen ?? state.edgeLen ?? 2); if (edgeModeInput) edgeModeInput.value = String(seg.edgeMode ?? state.edgeMode ?? 1); if (edgeGapInput) edgeGapInput.value = String(seg.edgeGap ?? state.edgeGap ?? 8); if (chaseBgPaletteInput) chaseBgPaletteInput.value = String(seg.chaseBg ?? state.chaseBg ?? 0); if (chasePaletteInput) chasePaletteInput.value = String(seg.chasePal ?? state.chasePal ?? 0); if (chaseLenInput) chaseLenInput.value = String(seg.chaseLen ?? state.chaseLen ?? 5); updateEffectControls(); if (paletteInput) paletteInput.value = String(selectedPaletteId); activatePaletteCard(selectedPaletteId); const selected = paletteCatalog.find(item => Number(item.id) === Number(selectedPaletteId)); if (selected && selected.editable) { if (editingPaletteId !== selected.id) loadPaletteEditor(selected.id); } else { editingPaletteId = null; editingStops = []; renderStopEditor(); } if (Array.isArray(color)) { colorInput.value = rgbToHex(color); } }\n"
    "    async function applyState() { const payload = buildStatePayload(); await fetch('/json/state', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); await loadState(); }\n"
    "    function buildStatePayload() { const [r, g, b] = hexToRgb(colorInput.value); return { on: true, paused: false, bri: Number(brightnessInput.value), color: [r, g, b], effect: Number(effectInput.value), speed: Number(speedInput.value), palette: Number(paletteInput.value), bgPal: Number(swooshBgPaletteInput.value), leftPal: Number(swooshLeftPaletteInput.value), rightPal: Number(swooshRightPaletteInput.value), leftStops: Number(sideLengthInput.value), rightStops: Number(sideLengthInput.value), shrinkBg: Number(shrinkBgPaletteInput.value), shrinkBar: Number(shrinkBarPaletteInput.value), shrinkLen: Number(shrinkLenInput.value), shrinkGap: Number(shrinkGapInput.value), rotBg: Number(rotationBgPaletteInput.value), rotPal: Number(rotationPaletteInput.value), rotLen: Number(rotationLenInput.value), rotGap: Number(rotationGapInput.value), rotCcw: !!rotationCcwInput.checked, ptPal: Number(pointPaletteInput.value), ptBg: Number(pointBgPaletteInput.value), ptLen: Number(pointLenInput.value), ptTotal: Number(pointTotalInput.value), ptMode: Number(pointModeInput.value), ptGap: Number(pointGapInput.value), edgePal: Number(edgePaletteInput.value), edgeLen: Number(edgeLenInput.value), edgeMode: Number(edgeModeInput.value), edgeGap: Number(edgeGapInput.value), chaseBg: Number(chaseBgPaletteInput.value), chasePal: Number(chasePaletteInput.value), chaseLen: Number(chaseLenInput.value) }; }\n"
    "    function escapeHtml(value) { return String(value ?? '').replace(/[&<>\"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', \"'\": '&#39;' }[ch])); }\n"
    "    function effectName(id) { const opt = effectInput ? [...effectInput.options].find(option => Number(option.value) === Number(id)) : null; return opt ? opt.textContent : `Effect ${id}`; }\n"
    "    function paletteName(id) { const item = paletteCatalog.find(entry => Number(entry.id) === Number(id)); return item ? item.name : `Palette ${id}`; }\n"
    "    function scenarioDetailLines(state) { const lines = []; const add = (label, value) => lines.push({ label, value }); add('Effect', effectName(state.effect)); add('Brightness', state.bri); add('Speed (flow speed)', state.speed); const fx = Number(state.effect); if (fx === 8 || fx === 9) { add('Background Palette', paletteName(state.bgPal)); add('Left Palette', paletteName(state.leftPal)); add('Right Palette', paletteName(state.rightPal)); add('Side Palette Length', state.leftStops); } else if (fx === 10) { add('Background Palette', paletteName(state.shrinkBg)); add('Bar Palette', paletteName(state.shrinkBar)); add('Shrink Length', state.shrinkLen); add('Gap (timing)', state.shrinkGap); } else if (fx === 11) { add('Background Palette', paletteName(state.rotBg)); add('Rotation Palette', paletteName(state.rotPal)); add('Rotation Length', state.rotLen); add('Gap (timing)', state.rotGap); add('Counterclockwise', state.rotCcw ? 'Yes' : 'No'); } else if (fx === 12) { add('Point Palette', paletteName(state.ptPal)); add('Background Palette', paletteName(state.ptBg)); add('Point Length', state.ptLen); add('Total Length', state.ptTotal); add('Repeat', state.ptMode); add('Gap (timing)', state.ptGap); } else if (fx === 13) { add('Edge Palette', paletteName(state.edgePal)); add('Edge Length', state.edgeLen); add('Repeat', state.edgeMode); add('Gap (timing)', state.edgeGap); } else if (fx === 3) { add('Background Palette', paletteName(state.chaseBg)); add('Chase Palette', paletteName(state.chasePal)); add('Chase Length', state.chaseLen); } else { add('Color Palette', paletteName(state.palette)); add('Primary Color', Array.isArray(state.color) ? rgbToHex(state.color).toUpperCase() : '-'); } return lines; }\n"
    "    function renderScenarios() { if (!scenarioList) return; scenarioList.innerHTML = ''; if (scenarioHint) scenarioHint.style.display = scenarios.length ? 'none' : ''; scenarios.forEach(item => { const row = document.createElement('div'); row.className = 'scenario-row'; row.dataset.id = item.id; row.title = 'Double-click to apply'; const label = document.createElement('div'); label.className = 'scenario-name'; label.innerHTML = `<strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(effectName(item.state.effect))}</span>`; const info = document.createElement('button'); info.type = 'button'; info.className = 'ghost scenario-info'; info.textContent = 'Details'; info.addEventListener('click', event => { event.stopPropagation(); showScenarioDetail(item.id); }); const del = document.createElement('button'); del.type = 'button'; del.className = 'ghost danger scenario-delete'; del.textContent = 'Delete'; del.addEventListener('click', event => { event.stopPropagation(); deleteScenario(item.id); }); row.append(label, info, del); row.addEventListener('dblclick', () => applyScenario(item.id)); scenarioList.appendChild(row); }); }\n"
    "    async function loadScenarios() { const response = await fetch('/json/scenarios'); const json = await response.json(); scenarios = Array.isArray(json.items) ? json.items.map(item => ({ id: item.id, name: item.name, state: item.state || {} })) : []; renderScenarios(); }\n"
    "    async function applyScenario(id) { const item = scenarios.find(entry => Number(entry.id) === Number(id)); if (!item) return; const payload = Object.assign({}, item.state, { on: true, paused: false }); await fetch('/json/state', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); await loadState(); }\n"
    "    function showScenarioDetail(id) { const item = scenarios.find(entry => Number(entry.id) === Number(id)); if (!item || !scenarioDetailDialog) return; detailScenarioId = Number(item.id); scenarioDetailTitle.textContent = item.name; scenarioDetailBody.innerHTML = scenarioDetailLines(item.state).map(line => `<div class=\"detail-row\"><span>${escapeHtml(line.label)}</span><strong>${escapeHtml(line.value)}</strong></div>`).join(''); if (typeof scenarioDetailDialog.showModal === 'function') scenarioDetailDialog.showModal(); }\n"
    "    function closeScenarioDetail() { detailScenarioId = null; if (scenarioDetailDialog && scenarioDetailDialog.open) scenarioDetailDialog.close(); }\n"
    "    async function deleteScenario(id) { const item = scenarios.find(entry => Number(entry.id) === Number(id)); if (!item) return; if (!window.confirm(`Delete scenario \"${item.name}\"?`)) return; const response = await fetch('/json/scenarios', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'delete', id: Number(id) }) }); if (!response.ok) return; if (Number(detailScenarioId) === Number(id)) closeScenarioDetail(); await loadScenarios(); }\n"
    "    function openSaveScenarioDialog() { if (!scenarioSaveDialog) return; scenarioNameInput.value = ''; if (typeof scenarioSaveDialog.showModal === 'function') scenarioSaveDialog.showModal(); scenarioNameInput.focus(); }\n"
    "    function closeSaveScenarioDialog() { if (scenarioSaveDialog && scenarioSaveDialog.open) scenarioSaveDialog.close(); }\n"
    "    async function confirmSaveScenario() { const name = (scenarioNameInput.value || '').trim(); if (!name) { scenarioNameInput.focus(); return; } const payload = { name, state: buildStatePayload() }; const response = await fetch('/json/scenarios', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) { scenarioNameInput.focus(); return; } closeSaveScenarioDialog(); await loadScenarios(); }\n"
    "    async function savePalette() { if (editingPaletteId === null) { editorHint.textContent = 'Select a custom palette before saving.'; return; } if (!editingStops.length) { editorHint.textContent = 'Add at least one color stop before saving.'; return; } const payload = { id: Number(editingPaletteId), name: customPaletteName.value.trim() || 'Custom Palette', circle: !!circlePaletteInput.checked, stops: editingStops.map(stop => [Number(stop.index), ...stop.rgb]) }; await fetch('/json/palettes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); await loadPalettes(); await loadState(); loadPaletteEditor(editingPaletteId); }\n"
    "    async function deletePalette() { if (editingPaletteId === null) { editorHint.textContent = 'Select a custom palette before deleting.'; return; } const item = paletteCatalog.find(entry => Number(entry.id) === Number(editingPaletteId)); if (!item || !item.editable) { editorHint.textContent = 'Only custom palettes can be deleted.'; return; } if (item.empty) { editorHint.textContent = 'This custom slot is already empty.'; return; } if (!window.confirm(`Delete custom palette \"${item.name}\"?`)) return; const deletedId = Number(editingPaletteId); await fetch('/json/palettes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'delete', id: deletedId }) }); editingPaletteId = null; editingStops = []; if (Number(selectedPaletteId) === deletedId) selectedPaletteId = 0; await loadPalettes(); await loadState(); }\n"
    "    async function exportBackup() { if (backupHint) backupHint.textContent = 'Preparing backup...'; try { const response = await fetch('/json/backup'); if (!response.ok) throw new Error('Export failed'); const data = await response.json(); const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); const stamp = new Date().toISOString().slice(0, 19).replace(/[:T]/g, '-'); link.href = url; link.download = `light-ring-backup-${stamp}.json`; document.body.appendChild(link); link.click(); document.body.removeChild(link); URL.revokeObjectURL(url); if (backupHint) backupHint.textContent = 'Backup downloaded.'; } catch (error) { if (backupHint) backupHint.textContent = error.message; } }\n"
    "    async function importBackup(file) { if (!file) return; if (backupHint) backupHint.textContent = 'Importing backup...'; try { const text = await file.text(); const data = JSON.parse(text); const payload = { palettes: Array.isArray(data.palettes) ? data.palettes : [], scenarios: Array.isArray(data.scenarios) ? data.scenarios : [] }; const response = await fetch('/json/backup', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error('Import failed'); editingPaletteId = null; editingStops = []; await loadPalettes(); await loadScenarios(); await loadState(); if (backupHint) backupHint.textContent = 'Backup imported.'; } catch (error) { if (backupHint) backupHint.textContent = error.message; } }\n"
    "    document.getElementById('applyBtn').addEventListener('click', applyState);\n"
    "    saveScenarioBtn.addEventListener('click', openSaveScenarioDialog);\n"
    "    reloadScenariosBtn.addEventListener('click', () => loadScenarios().catch(error => { deviceInfo.textContent = error.message; }));\n"
    "    scenarioSaveCancelBtn.addEventListener('click', closeSaveScenarioDialog);\n"
    "    scenarioSaveConfirmBtn.addEventListener('click', confirmSaveScenario);\n"
    "    scenarioNameInput.addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); confirmSaveScenario(); } });\n"
    "    scenarioDetailCloseBtn.addEventListener('click', closeScenarioDetail);\n"
    "    if (scenarioSaveDialog) scenarioSaveDialog.addEventListener('cancel', event => { event.preventDefault(); closeSaveScenarioDialog(); });\n"
    "    if (scenarioDetailDialog) scenarioDetailDialog.addEventListener('cancel', event => { event.preventDefault(); closeScenarioDetail(); });\n"
    "    document.getElementById('toggleBtn').addEventListener('click', async () => { await fetch(`/win?T=${lastOn ? 0 : 1}`); await loadState(); });\n"
    "    suspendBtn.addEventListener('click', async () => { await fetch('/json/state', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paused: !lastPaused }) }); await loadState(); });\n"
    "    effectInput.addEventListener('change', updateEffectControls);\n"
    "    paletteInput.addEventListener('change', () => { selectedPaletteId = Number(paletteInput.value); activatePaletteCard(selectedPaletteId); const selected = paletteCatalog.find(item => Number(item.id) === Number(selectedPaletteId)); if (selected && selected.editable) { loadPaletteEditor(selected.id); } else { editingPaletteId = null; editingStops = []; renderStopEditor(); } });\n"
    "    stopList.addEventListener('input', event => { const target = event.target; const index = Number(target.dataset.index); if (Number.isNaN(index) || !editingStops[index]) return; if (target.dataset.role === 'index') { editingStops[index].index = Math.max(0, Math.min(255, Number(target.value) || 0)); editingStops.sort((a, b) => a.index - b.index); renderStopEditor(); } });\n"
    "    stopList.addEventListener('input', event => { const target = event.target; if (target.dataset.role !== 'index-led') return; const index = Number(target.dataset.index); if (Number.isNaN(index) || !editingStops[index]) return; const ledIndex = clampLedIndex(target.value); editingStops[index].index = ledIndexToPaletteIndex(ledIndex, editingPaletteCircle); renderPreview(editorPreview, previewColorsFromStops(editingStops, editingPaletteCircle)); });\n"
    "    stopList.addEventListener('change', event => { const target = event.target; if (target.dataset.role !== 'index-led') return; const index = Number(target.dataset.index); if (Number.isNaN(index) || !editingStops[index]) return; const ledIndex = clampLedIndex(target.value); target.value = String(ledIndex); editingStops[index].index = ledIndexToPaletteIndex(ledIndex, editingPaletteCircle); editingStops.sort((a, b) => a.index - b.index); renderStopEditor(); });\n"
    "    stopList.addEventListener('click', event => { const target = event.target; if (target.dataset.role === 'edit-color') { const index = Number(target.dataset.index); if (!Number.isNaN(index)) openColorDialog(index); return; } if (target.dataset.role !== 'remove') return; const index = Number(target.dataset.index); if (!Number.isNaN(index)) { editingStops.splice(index, 1); renderStopEditor(); } });\n"
    "    addStopBtn.addEventListener('click', () => { if (editingPaletteId === null) { editorHint.textContent = 'Select a custom palette first.'; return; } if (editingStops.length >= 27) return; editingStops.push({ index: editingStops.length ? Math.min(255, editingStops[editingStops.length - 1].index + 32) : 0, rgb: [255, 255, 255] }); renderStopEditor(); });\n"
    "    circlePaletteInput.addEventListener('change', () => { editingPaletteCircle = !!circlePaletteInput.checked; renderStopEditor(); });\n"
    "    savePaletteBtn.addEventListener('click', savePalette);\n"
    "    if (deletePaletteBtn) deletePaletteBtn.addEventListener('click', deletePalette);\n"
    "    newPaletteBtn.addEventListener('click', startNewPalette);\n"
    "    dialogCancelBtn.addEventListener('click', closeColorDialog);\n"
    "    dialogApplyBtn.addEventListener('click', applyDialogColor);\n"
    "    dialogColorPicker.addEventListener('input', () => syncDialogFromRgb(hexToRgb(dialogColorPicker.value)));\n"
    "    dialogHexInput.addEventListener('input', () => { const normalized = normalizeHexInput(dialogHexInput.value); if (normalized === null) return; dialogHexInput.value = normalized.toUpperCase(); if (!isCompleteHex(normalized)) return; syncDialogFromRgb(hexToRgb(normalized)); });\n"
    "    [dialogRedInput, dialogGreenInput, dialogBlueInput].forEach(input => input.addEventListener('input', () => syncDialogFromRgb(dialogRgb())));\n"
    "    if (colorDialog) colorDialog.addEventListener('cancel', event => { event.preventDefault(); closeColorDialog(); });\n"
    "    reloadPalettesBtn.addEventListener('click', () => loadPalettes().then(loadState).catch(error => { deviceInfo.textContent = error.message; }));\n"
    "    if (exportBackupBtn) exportBackupBtn.addEventListener('click', exportBackup);\n"
    "    if (importBackupBtn) importBackupBtn.addEventListener('click', () => { if (importBackupInput) importBackupInput.click(); });\n"
    "    if (importBackupInput) importBackupInput.addEventListener('change', event => { const file = event.target.files && event.target.files[0]; importBackup(file); event.target.value = ''; });\n"
    "    Promise.all([loadInfo(), loadPalettes(), loadScenarios()]).then(loadState).catch(error => { deviceInfo.textContent = error.message; });\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n";

esp_err_t ui_page_send(httpd_req_t *req)
{
    set_common_response_headers(req, "text/html; charset=utf-8");
    httpd_resp_send_chunk(req, UI_PAGE_HEAD, HTTPD_RESP_USE_STRLEN);
    httpd_resp_send_chunk(req, UI_EFFECT_HTML, HTTPD_RESP_USE_STRLEN);
    httpd_resp_send_chunk(req, UI_PALETTE_GALLERY_HTML, HTTPD_RESP_USE_STRLEN);
    httpd_resp_send_chunk(req, UI_PAGE_COLUMN_BREAK, HTTPD_RESP_USE_STRLEN);
    httpd_resp_send_chunk(req, UI_SCENARIO_HTML, HTTPD_RESP_USE_STRLEN);
    httpd_resp_send_chunk(req, UI_PALETTE_EDITOR_HTML, HTTPD_RESP_USE_STRLEN);
    httpd_resp_send_chunk(req, UI_BACKUP_HTML, HTTPD_RESP_USE_STRLEN);
    httpd_resp_send_chunk(req, UI_PAGE_STRUCT_CLOSE, HTTPD_RESP_USE_STRLEN);
    httpd_resp_send_chunk(req, UI_PALETTE_DIALOG_HTML, HTTPD_RESP_USE_STRLEN);
    httpd_resp_send_chunk(req, UI_SCENARIO_DIALOGS_HTML, HTTPD_RESP_USE_STRLEN);
    httpd_resp_send_chunk(req, UI_PAGE_TAIL, HTTPD_RESP_USE_STRLEN);
    return httpd_resp_send_chunk(req, NULL, 0);
}
