#include "ui_palette.h"

const char UI_PALETTE_GALLERY_HTML[] =
    "        <div class=\"card\">\n"
    "          <div class=\"editor-header\">\n"
    "            <div>\n"
    "              <h2>Palette Gallery</h2>\n"
    "              <p class=\"note\">Built-ins are read-only. Eight custom slots can be edited, saved to flash, and optionally wrapped as a ring.</p>\n"
    "            </div>\n"
    "            <div class=\"actions\">\n"
    "              <button id=\"newPaletteBtn\" type=\"button\">New Custom Palette</button>\n"
    "              <button id=\"reloadPalettesBtn\" class=\"ghost\" type=\"button\">Reload</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div id=\"paletteGallery\" class=\"palette-grid\"></div>\n"
    "        </div>\n";

const char UI_PALETTE_EDITOR_HTML[] =
    "        <div class=\"card\">\n"
    "          <h2>Custom Palette Editor</h2>\n"
    "          <p id=\"editorHint\" class=\"note\">Select a custom palette card to edit its color stops.</p>\n"
    "          <div class=\"editor-shell\">\n"
    "            <div class=\"row editor-options\">\n"
    "              <div>\n"
    "                <label for=\"customPaletteName\">Palette Name</label>\n"
    "                <input id=\"customPaletteName\" type=\"text\" maxlength=\"23\" placeholder=\"Custom palette name\">\n"
    "              </div>\n"
    "              <label class=\"toggle-row\" for=\"circlePaletteInput\"><input id=\"circlePaletteInput\" type=\"checkbox\"><span>Circle Palette</span></label>\n"
    "            </div>\n"
    "            <div id=\"editorPreview\" class=\"palette-preview\"></div>\n"
    "            <div class=\"toolbar\">\n"
    "              <button id=\"addStopBtn\" class=\"ghost\" type=\"button\">Add Stop</button>\n"
    "              <button id=\"savePaletteBtn\" type=\"button\">Save Palette</button>\n"
    "            </div>\n"
    "            <div id=\"stopList\" class=\"stop-list\"></div>\n"
    "          </div>\n"
    "        </div>\n";

const char UI_PALETTE_DIALOG_HTML[] =
    "    <dialog id=\"colorDialog\" class=\"color-dialog\">\n"
    "      <div class=\"dialog-body\">\n"
    "        <div>\n"
    "          <h2>Edit Stop Color</h2>\n"
    "          <p id=\"colorDialogHint\" class=\"note\">Tune this stop using the picker, HEX, or RGB values.</p>\n"
    "        </div>\n"
    "        <div class=\"dialog-grid\">\n"
    "          <div class=\"wide\"><label for=\"dialogColorPicker\">Color</label><input id=\"dialogColorPicker\" type=\"color\"></div>\n"
    "          <div class=\"wide\"><label for=\"dialogHexInput\">HEX</label><input id=\"dialogHexInput\" type=\"text\" maxlength=\"7\" placeholder=\"#RRGGBB\" spellcheck=\"false\"></div>\n"
    "          <div><label for=\"dialogRedInput\">R</label><input id=\"dialogRedInput\" type=\"number\" min=\"0\" max=\"255\"></div>\n"
    "          <div><label for=\"dialogGreenInput\">G</label><input id=\"dialogGreenInput\" type=\"number\" min=\"0\" max=\"255\"></div>\n"
    "          <div><label for=\"dialogBlueInput\">B</label><input id=\"dialogBlueInput\" type=\"number\" min=\"0\" max=\"255\"></div>\n"
    "        </div>\n"
    "        <div class=\"dialog-actions\">\n"
    "          <button id=\"dialogCancelBtn\" class=\"ghost\" type=\"button\">Cancel</button>\n"
    "          <button id=\"dialogApplyBtn\" type=\"button\">Apply Color</button>\n"
    "        </div>\n"
    "      </div>\n"
    "    </dialog>\n";
