#include "ui_scenario.h"

const char UI_SCENARIO_HTML[] =
    "        <div class=\"card\">\n"
    "          <div class=\"editor-header\">\n"
    "            <div>\n"
    "              <h2>Scenarios</h2>\n"
    "              <p class=\"note\">Double-click a scenario to apply it to the Effect panel. Use Details to inspect its parameters.</p>\n"
    "            </div>\n"
    "            <div class=\"actions\">\n"
    "              <button id=\"reloadScenariosBtn\" class=\"ghost\" type=\"button\">Reload</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div id=\"scenarioList\" class=\"scenario-list\"></div>\n"
    "          <p id=\"scenarioHint\" class=\"note\">No scenarios saved yet. Configure the Effect panel, then press Save Scenario.</p>\n"
    "        </div>\n";

const char UI_SCENARIO_DIALOGS_HTML[] =
    "    <dialog id=\"scenarioSaveDialog\" class=\"color-dialog\">\n"
    "      <div class=\"dialog-body\">\n"
    "        <div>\n"
    "          <h2>Save Scenario</h2>\n"
    "          <p class=\"note\">Name this scenario to store the current Effect settings.</p>\n"
    "        </div>\n"
    "        <div><label for=\"scenarioNameInput\">Scenario Name</label><input id=\"scenarioNameInput\" type=\"text\" maxlength=\"31\" placeholder=\"e.g. Sunset Glow\" spellcheck=\"false\"></div>\n"
    "        <div class=\"dialog-actions\">\n"
    "          <button id=\"scenarioSaveCancelBtn\" class=\"ghost\" type=\"button\">Cancel</button>\n"
    "          <button id=\"scenarioSaveConfirmBtn\" type=\"button\">Save</button>\n"
    "        </div>\n"
    "      </div>\n"
    "    </dialog>\n"
    "    <dialog id=\"scenarioDetailDialog\" class=\"color-dialog\">\n"
    "      <div class=\"dialog-body\">\n"
    "        <div>\n"
    "          <h2 id=\"scenarioDetailTitle\">Scenario</h2>\n"
    "          <p class=\"note\">Key parameters for this saved scenario.</p>\n"
    "        </div>\n"
    "        <div id=\"scenarioDetailBody\" class=\"scenario-detail-list\"></div>\n"
    "        <div class=\"dialog-actions\">\n"
    "          <button id=\"scenarioDetailCloseBtn\" type=\"button\">Close</button>\n"
    "        </div>\n"
    "      </div>\n"
    "    </dialog>\n";
